sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.3.0
env:
  - ACTIVERECORD=3.0.0
  - ACTIVERECORD=3.2.0
  - ACTIVERECORD=4.0.0
  - ACTIVERECORD=4.2.0
matrix:
  exclude:
  allow_failures:
    - rvm: rbx
  fast_finish: true
